- alias: Yamaha on/off
  hide_entity: true
  trigger:
    platform: state
    entity_id: media_player.living_room_main
  action:
    service_template: "{% if (trigger.to_state.state == 'off') %} switch.turn_off {% else %}  switch.turn_on {%endif %}"
    data_template:
      entity_id: "switch.musa"

- alias: TV on
  hide_entity: true
  trigger:
    platform: state
    entity_id: media_player.sony_bravia_tv
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: media_player.living_room_main
    state: 'off'
  action:
    - service: media_player.turn_on
      data:
        entity_id: media_player.living_room_main
    - wait_template: "{{ states.media_player.living_room_main.state == 'on' }}"
      timeout: 00:00:10
    - service: media_player.select_source
      data:
        entity_id: media_player.living_room_main
        source: optical

- alias: TV off
  hide_entity: true
  trigger:
    platform: state
    entity_id: media_player.sony_bravia_tv
    from: 'on'
    to: 'off'
  condition:
    condition: template
    value_template: '{{ is_state_attr("media_player.living_room_main","source","optical") }}'
  action:
    service: media_player.turn_off
    data:
      entity_id: media_player.living_room_main

- alias: Left rocker
  hide_entity: true
  trigger:
    platform: event
    event_type: button_pressed
    event_data:
      which: 1
      pushed: 1
  action:
    service_template: "{% if trigger.event.data.onoff %} homeassistant.turn_off {% else %}  homeassistant.turn_on {%endif %}"
    data_template:
      entity_id: "media_player.living_room_main"

- alias: Right rocker
  hide_entity: true
  trigger:
    platform: event
    event_type: button_pressed
    event_data:
      which: 0
      pushed: 1
  action:
    service_template: "{% if trigger.event.data.onoff %} homeassistant.turn_off {% else %}  homeassistant.turn_on {%endif %}"
    data_template:
      entity_id: "group.livingroom"

- alias: Both rockers
  hide_entity: true
  trigger:
    platform: event
    event_type: button_pressed
    event_data:
      which: 10
      pushed: 1
  action:
    service_template: "{% if trigger.event.data.onoff %} switch.turn_off {% else %}  switch.turn_on {%endif %}"
    data_template:
      entity_id: "switch.tietokone"

- alias: Flux jalkalamppu
  hide_entity: false
  trigger:
    - platform: time
      seconds: '/30'
    - platform: state
      entity_id: light.jalkalamppu
      from: 'off'
      to: 'on'
  condition:
    condition: state
    entity_id: light.jalkalamppu
    state: 'on'
  action:
    service: light.turn_on
    data_template:
      entity_id: "light.jalkalamppu"
      brightness: >
        {% if now().hour < 6 %}
          150
        {% elif now().hour < 16 %}
          254
        {% else %}
          {{ ((254 - 150) * (1 - ((now().hour + now().minute/60.0) - 16.0) / 8.0) + 150) | int }}
        {% endif %}
      kelvin: >
        {% if now().hour < 6 %}
          2200
        {% elif now().hour < 16 %}
          4000
        {% elif now().hour < 18 %}
          2700
        {% else %}
          2200
        {% endif %}

- alias: Flux pallo
  hide_entity: false
  trigger:
    - platform: time
      seconds: '/30'
    - platform: state
      entity_id: light.pallo
      from: 'off'
      to: 'on'
  condition:
    condition: state
    entity_id: light.pallo
    state: 'on'
  action:
    service: light.turn_on
    data_template:
      entity_id: "light.pallo"
      brightness: >
        {% if now().hour < 6 %}
          150
        {% elif now().hour < 16 %}
          254
        {% else %}
          {{ ((254 - 150) * (1 - ((now().hour + now().minute/60.0) - 16.0) / 8.0) + 150) | int }}
        {% endif %}
      kelvin: >
        {% if now().hour < 6 %}
          2200
        {% elif now().hour < 16 %}
          4000
        {% elif now().hour < 18 %}
          2700
        {% else %}
          2200
        {% endif %}

- alias: Flux ruokapoyta
  hide_entity: false
  trigger:
    - platform: time
      seconds: '/30'
    - platform: state
      entity_id: light.ruokapoyta
      from: 'off'
      to: 'on'
  condition:
    condition: state
    entity_id: light.ruokapoyta
    state: 'on'
  action:
    service: light.turn_on
    data_template:
      entity_id: "light.ruokapoyta"
      brightness: >
        {% if now().hour < 6 %}
          150
        {% elif now().hour < 16 %}
          254
        {% else %}
          {{ ((254 - 150) * (1 - ((now().hour + now().minute/60.0) - 16.0) / 8.0) + 150) | int }}
        {% endif %}
      kelvin: >
        {% if now().hour < 6 %}
          2200
        {% elif now().hour < 16 %}
          4000
        {% elif now().hour < 18 %}
          2700
        {% else %}
          2200
        {% endif %}

- alias: Flux spotti 1
  hide_entity: false
  trigger:
    - platform: time
      seconds: '/30'
    - platform: state
      entity_id: light.spotti_1
      from: 'off'
      to: 'on'
  condition:
    condition: state
    entity_id: light.spotti_1
    state: 'on'
  action:
    service: light.turn_on
    data_template:
      entity_id: "light.spotti_1"
      brightness: >
        {% if now().hour < 6 %}
          150
        {% elif now().hour < 16 %}
          254
        {% else %}
          {{ ((254 - 150) * (1 - ((now().hour + now().minute/60.0) - 16.0) / 8.0) + 150) | int }}
        {% endif %}
      kelvin: >
        {% if now().hour < 6 %}
          2200
        {% elif now().hour < 16 %}
          4000
        {% elif now().hour < 18 %}
          2700
        {% else %}
          2200
        {% endif %}

- alias: Flux spotti 2
  hide_entity: false
  trigger:
    - platform: time
      seconds: '/30'
    - platform: state
      entity_id: light.spotti_2
      from: 'off'
      to: 'on'
  condition:
    condition: state
    entity_id: light.spotti_2
    state: 'on'
  action:
    service: light.turn_on
    data_template:
      entity_id: "light.spotti_2"
      brightness: >
        {% if now().hour < 6 %}
          150
        {% elif now().hour < 16 %}
          254
        {% else %}
          {{ ((254 - 150) * (1 - ((now().hour + now().minute/60.0) - 16.0) / 8.0) + 150) | int }}
        {% endif %}
      kelvin: >
        {% if now().hour < 6 %}
          2200
        {% elif now().hour < 16 %}
          4000
        {% elif now().hour < 18 %}
          2700
        {% else %}
          2200
        {% endif %}

- alias: Flux spotti 3
  hide_entity: false
  trigger:
    - platform: time
      seconds: '/30'
    - platform: state
      entity_id: light.spotti_3
      from: 'off'
      to: 'on'
  condition:
    condition: state
    entity_id: light.spotti_3
    state: 'on'
  action:
    service: light.turn_on
    data_template:
      entity_id: "light.spotti_3"
      brightness: >
        {% if now().hour < 6 %}
          150
        {% elif now().hour < 16 %}
          254
        {% else %}
          {{ ((254 - 150) * (1 - ((now().hour + now().minute/60.0) - 16.0) / 8.0) + 150) | int }}
        {% endif %}
      kelvin: >
        {% if now().hour < 6 %}
          2200
        {% elif now().hour < 16 %}
          4000
        {% elif now().hour < 18 %}
          2700
        {% else %}
          2200
        {% endif %}

- alias: Flux katto
  hide_entity: false
  trigger:
    - platform: time
      seconds: '/30'
    - platform: state
      entity_id: light.katto
      from: 'off'
      to: 'on'
  condition:
    condition: state
    entity_id: light.katto
    state: 'on'
  action:
    service: light.turn_on
    data_template:
      entity_id: "light.katto"
      brightness: >
        {% if now().hour < 6 %}
          50
        {% elif now().hour < 16 %}
          254
        {% else %}
          {{ ((254 - 50) * (1 - ((now().hour + now().minute/60.0) - 16.0) / 8.0) + 50) | int }}
        {% endif %}
      kelvin: >
        {% if now().hour < 6 %}
          2200
        {% elif now().hour < 16 %}
          4000
        {% elif now().hour < 18 %}
          2700
        {% else %}
          2200
        {% endif %}
