- id: tv_on
  alias: TV on
  trigger:
    platform: state
    entity_id: media_player.sony_bravia_tv
    to: 'on'
  action:
    - service: light.turn_on
      entity_id: light.musa

- id: tv_off
  alias: TV off
  trigger:
    platform: state
    entity_id: media_player.sony_bravia_tv
    to: 'off'
  action:
    - service: light.turn_off
      entity_id: light.musa
