homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 6
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Helsinki
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

logger:
#  default: critical
#  logs:
#    homeassistant.components.enocean: debug

# Track the sun
#sun:

# Weather Prediction
#sensor:
#  platform: yr

# Text to speech
tts:
  platform: google

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

emulated_hue:
  host_ip: 10.0.1.12
  listen_port: 8300
  type: alexa

media_player:
  - platform: braviatv
    host: 10.0.1.23

enocean:
  device: /dev/ttyAMA0

binary_sensor:
  - platform: enocean
    id: [0xFE,0xFD,0x8A,0x5A]
    name: enocean_binary_sensor_1
  - platform: enocean
    id: [0xFE,0xFD,0x52,0x0A]
    name: enocean_binary_sensor_2

tradfri:
  host: 10.0.1.11
  api_key: !secret api_key
  allow_tradfri_groups: false

switch:
  - platform: template
    switches:
      musa:
        value_template: "{{ is_state('light.musa', 'on') }}"
        turn_on:
          service: light.turn_on
          entity_id: light.musa
        turn_off:
          service: light.turn_off
          entity_id: light.musa
        entity_id: light.musa
      tietokone:
        value_template: "{{ is_state('light.tietokone', 'on') }}"
        turn_on:
          service: light.turn_on
          entity_id: light.tietokone
        turn_off:
          service: light.turn_off
          entity_id: light.tietokone
        entity_id: light.tietokone
      sony_bravia_tv:
        friendly_name: TV
        value_template: "{{ is_state('media_player.sony_bravia_tv', 'on') }}"
        turn_on:
          service: media_player.turn_on
          entity_id: media_player.sony_bravia_tv
        turn_off:
          service: media_player.turn_off
          entity_id: media_player.sony_bravia_tv
        entity_id: media_player.sony_bravia_tv
